name: silkreto
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  image_picker: ^0.8.7+5
  sqflite: ^2.3.0
  path: ^1.8.3
  intl: ^0.19.0
  google_fonts: ^5.0.0
  fl_chart: ^1.1.1
  permission_handler: ^11.3.1
  tflite_flutter: ^0.12.1
  image: ^4.7.2
  path_provider: ^2.1.3
  http: ^1.6.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  camera: ^0.11.3
  pathfinding: ^3.0.1
  app_settings: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/Silkreto-Logo.png
    - assets/weather-clouds/more-cloudy-sunny.png
    - assets/weather-clouds/rainy-thunder.png
    - assets/weather-clouds/rainy.png
    - assets/weather-clouds/sunny-cloudy.png
    - assets/weather-clouds/sunny.png
    - assets/weather-clouds/darkcloud-thunder.png
    - assets/Explore/Diseases.png
    - assets/Explore/Prevention.png
    - assets/Explore/Rearing.png
    - assets/Explore/Symptoms.png
    - assets/model/best_float32.tflite
    - assets/silkreto-logo-square.jpg
    - assets/silkreto-logo-png.png
    - assets/silkreto-logo-bg.jpg

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/silkreto-logo-square.jpg
